/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto1;

/**
 *
 * @author dantiii
 */
public class FrameFarmInfrastructure extends javax.swing.JFrame {

    /**
     * Creates new form FrameFarmInfrastructure
     */
    public FrameFarmInfrastructure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        farmer1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        farmer2 = new javax.swing.JTextField();
        farmer3 = new javax.swing.JTextField();
        farmer4 = new javax.swing.JTextField();
        farmer5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        standinArea1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        standinArea2 = new javax.swing.JTextField();
        standinArea3 = new javax.swing.JTextField();
        standinArea4 = new javax.swing.JTextField();
        standinArea5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        path11 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        path12 = new javax.swing.JTextField();
        path13 = new javax.swing.JTextField();
        path14 = new javax.swing.JTextField();
        standinArea15 = new javax.swing.JTextField();
        path22 = new javax.swing.JTextField();
        path23 = new javax.swing.JTextField();
        path24 = new javax.swing.JTextField();
        standinArea25 = new javax.swing.JTextField();
        path21 = new javax.swing.JTextField();
        path15 = new javax.swing.JTextField();
        path16 = new javax.swing.JTextField();
        path17 = new javax.swing.JTextField();
        standinArea16 = new javax.swing.JTextField();
        path25 = new javax.swing.JTextField();
        path26 = new javax.swing.JTextField();
        path27 = new javax.swing.JTextField();
        standinArea26 = new javax.swing.JTextField();
        path28 = new javax.swing.JTextField();
        path18 = new javax.swing.JTextField();
        path19 = new javax.swing.JTextField();
        path20 = new javax.swing.JTextField();
        path29 = new javax.swing.JTextField();
        path30 = new javax.swing.JTextField();
        standinArea17 = new javax.swing.JTextField();
        path31 = new javax.swing.JTextField();
        path32 = new javax.swing.JTextField();
        standinArea18 = new javax.swing.JTextField();
        path33 = new javax.swing.JTextField();
        path34 = new javax.swing.JTextField();
        path35 = new javax.swing.JTextField();
        path36 = new javax.swing.JTextField();
        standinArea27 = new javax.swing.JTextField();
        path37 = new javax.swing.JTextField();
        path38 = new javax.swing.JTextField();
        standinArea28 = new javax.swing.JTextField();
        path39 = new javax.swing.JTextField();
        path40 = new javax.swing.JTextField();
        path41 = new javax.swing.JTextField();
        path42 = new javax.swing.JTextField();
        path43 = new javax.swing.JTextField();
        standinArea19 = new javax.swing.JTextField();
        path44 = new javax.swing.JTextField();
        path45 = new javax.swing.JTextField();
        path46 = new javax.swing.JTextField();
        standinArea29 = new javax.swing.JTextField();
        path47 = new javax.swing.JTextField();
        path48 = new javax.swing.JTextField();
        path49 = new javax.swing.JTextField();
        path50 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        granary1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        granary2 = new javax.swing.JTextField();
        granary3 = new javax.swing.JTextField();
        granary4 = new javax.swing.JTextField();
        granary5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farm Infrastructure");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        farmer1.setEditable(false);
        farmer1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        farmer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        farmer1.setText("1");
        farmer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Storehouse");

        farmer2.setEditable(false);
        farmer2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        farmer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        farmer2.setText("2");
        farmer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        farmer3.setEditable(false);
        farmer3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        farmer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        farmer3.setText("3");
        farmer3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        farmer4.setEditable(false);
        farmer4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        farmer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        farmer4.setText("4");
        farmer4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        farmer5.setEditable(false);
        farmer5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        farmer5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        farmer5.setText("5");
        farmer5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(farmer2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmer1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmer3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmer4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(farmer5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(farmer1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(farmer2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(farmer3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(farmer4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(farmer5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        standinArea1.setEditable(false);
        standinArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Standing");

        standinArea2.setEditable(false);
        standinArea2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea3.setEditable(false);
        standinArea3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea4.setEditable(false);
        standinArea4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea5.setEditable(false);
        standinArea5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(standinArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standinArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standinArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standinArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(standinArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(standinArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(standinArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(standinArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(standinArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(standinArea5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        path11.setEditable(false);
        path11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Path");

        path12.setEditable(false);
        path12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path13.setEditable(false);
        path13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path14.setEditable(false);
        path14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea15.setEditable(false);
        standinArea15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path22.setEditable(false);
        path22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path23.setEditable(false);
        path23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path24.setEditable(false);
        path24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea25.setEditable(false);
        standinArea25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path21.setEditable(false);
        path21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path15.setEditable(false);
        path15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path16.setEditable(false);
        path16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path17.setEditable(false);
        path17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea16.setEditable(false);
        standinArea16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path25.setEditable(false);
        path25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path26.setEditable(false);
        path26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path27.setEditable(false);
        path27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea26.setEditable(false);
        standinArea26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path28.setEditable(false);
        path28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path18.setEditable(false);
        path18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path19.setEditable(false);
        path19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path20.setEditable(false);
        path20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path29.setEditable(false);
        path29.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path30.setEditable(false);
        path30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea17.setEditable(false);
        standinArea17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path31.setEditable(false);
        path31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path32.setEditable(false);
        path32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea18.setEditable(false);
        standinArea18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path33.setEditable(false);
        path33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path34.setEditable(false);
        path34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path35.setEditable(false);
        path35.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path36.setEditable(false);
        path36.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea27.setEditable(false);
        standinArea27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path37.setEditable(false);
        path37.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path38.setEditable(false);
        path38.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea28.setEditable(false);
        standinArea28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path39.setEditable(false);
        path39.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path40.setEditable(false);
        path40.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path41.setEditable(false);
        path41.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path42.setEditable(false);
        path42.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path43.setEditable(false);
        path43.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea19.setEditable(false);
        standinArea19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path44.setEditable(false);
        path44.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path45.setEditable(false);
        path45.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path46.setEditable(false);
        path46.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        standinArea29.setEditable(false);
        standinArea29.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        standinArea29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        standinArea29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path47.setEditable(false);
        path47.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path48.setEditable(false);
        path48.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path49.setEditable(false);
        path49.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path49.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        path50.setEditable(false);
        path50.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        path50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        path50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path41, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path40, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path37, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path42, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path39, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path38, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path49, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path48, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path50, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path43, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(standinArea19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path44, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path47, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path45, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(path46, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(standinArea29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path48, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path49, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path50, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path43, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(standinArea19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(standinArea29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path47, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path44, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path45, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path46, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path39, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path42, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path38, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path32, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path33, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path35, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path41, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path31, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path40, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path34, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path36, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path37, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea16, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(path28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(path27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(standinArea26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(path12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(path13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(path14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(standinArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(path21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(path11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addComponent(path22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(path23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(path24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(standinArea25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        granary1.setEditable(false);
        granary1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        granary1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granary1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Granary");

        granary2.setEditable(false);
        granary2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        granary2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granary2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        granary3.setEditable(false);
        granary3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        granary3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granary3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        granary4.setEditable(false);
        granary4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        granary4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granary4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        granary5.setEditable(false);
        granary5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        granary5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        granary5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(granary2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(granary1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(granary3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(granary4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(granary5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(granary1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(granary2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(granary3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(granary4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(granary5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFarmInfrastructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField farmer1;
    private javax.swing.JTextField farmer2;
    private javax.swing.JTextField farmer3;
    private javax.swing.JTextField farmer4;
    private javax.swing.JTextField farmer5;
    private javax.swing.JTextField granary1;
    private javax.swing.JTextField granary2;
    private javax.swing.JTextField granary3;
    private javax.swing.JTextField granary4;
    private javax.swing.JTextField granary5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField path11;
    private javax.swing.JTextField path12;
    private javax.swing.JTextField path13;
    private javax.swing.JTextField path14;
    private javax.swing.JTextField path15;
    private javax.swing.JTextField path16;
    private javax.swing.JTextField path17;
    private javax.swing.JTextField path18;
    private javax.swing.JTextField path19;
    private javax.swing.JTextField path20;
    private javax.swing.JTextField path21;
    private javax.swing.JTextField path22;
    private javax.swing.JTextField path23;
    private javax.swing.JTextField path24;
    private javax.swing.JTextField path25;
    private javax.swing.JTextField path26;
    private javax.swing.JTextField path27;
    private javax.swing.JTextField path28;
    private javax.swing.JTextField path29;
    private javax.swing.JTextField path30;
    private javax.swing.JTextField path31;
    private javax.swing.JTextField path32;
    private javax.swing.JTextField path33;
    private javax.swing.JTextField path34;
    private javax.swing.JTextField path35;
    private javax.swing.JTextField path36;
    private javax.swing.JTextField path37;
    private javax.swing.JTextField path38;
    private javax.swing.JTextField path39;
    private javax.swing.JTextField path40;
    private javax.swing.JTextField path41;
    private javax.swing.JTextField path42;
    private javax.swing.JTextField path43;
    private javax.swing.JTextField path44;
    private javax.swing.JTextField path45;
    private javax.swing.JTextField path46;
    private javax.swing.JTextField path47;
    private javax.swing.JTextField path48;
    private javax.swing.JTextField path49;
    private javax.swing.JTextField path50;
    private javax.swing.JTextField standinArea1;
    private javax.swing.JTextField standinArea15;
    private javax.swing.JTextField standinArea16;
    private javax.swing.JTextField standinArea17;
    private javax.swing.JTextField standinArea18;
    private javax.swing.JTextField standinArea19;
    private javax.swing.JTextField standinArea2;
    private javax.swing.JTextField standinArea25;
    private javax.swing.JTextField standinArea26;
    private javax.swing.JTextField standinArea27;
    private javax.swing.JTextField standinArea28;
    private javax.swing.JTextField standinArea29;
    private javax.swing.JTextField standinArea3;
    private javax.swing.JTextField standinArea4;
    private javax.swing.JTextField standinArea5;
    // End of variables declaration//GEN-END:variables
}
